- name: vim add repository
  apt_repository:
    repo: ppa:jonathonf/vim
    state: present
  tags: vim
- name: vim update
  apt:
    update_cache: yes
  tags: vim
- name: vim install
  apt:
    name: vim
    state: present
  tags: vim
- name: vim get config
  get_url:
    url: https://raw.githubusercontent.com/matusstafura/dotfiles/refs/heads/main/vim/vimrc
    dest: /home/{{ ansible_user }}/.vimrc
  tags: vim

