- name: clone latest vim
  ansible.builtin.git:
    repo: 'https://github.com/vim/vim.git'
    dest: /home/{{ ansible_user }}/vim
    update: yes
  tags: vim

- name: build vim
  ansible.builtin.shell: |
    apt install -y git make clang libtool-bin 
    cd /home/{{ ansible_user }}/vim/src
    make
    make install
  tags: vim

