- name: Install powerlevel10k
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git 
    dest: /home/{{ ansible_user }}/.oh-my-zsh/custom/themes/powerlevel10k
    depth: 1

- name: Add powerlevel10k to zshrc
  ansible.builtin.lineinfile: 
    path: /home/{{ ansible_user }}/.zshrc
    insertbefore: BOF
    line: 'ZSH_THEME="powerlevel10k/powerlevel10k"'

- name: Add powerlevel10k to zshrc
  ansible.builtin.lineinfile: 
    path: /home/{{ ansible_user }}/.zshrc
    line: '[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh'

- name: Disable Wizard
  ansible.builtin.lineinfile: 
    path: /home/{{ ansible_user }}/.zshrc
    line: 'POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true'


