- name: Install zsh
  ansible.builtin.package: 
    name: zsh
    state: present

- name: Set user shell to zsh
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh
  become: true

- name: Download ohmyzsh
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: /home/{{ ansible_user }}/.oh-my-zsh
    depth: 1

- name: Add zshrc to user
  ansible.builtin.lineinfile:
    path: /home/{{ ansible_user }}/.zshrc
    line: "export ZSH=~/.oh-my-zsh"
    create: yes

- name: Add zshrc to user
  ansible.builtin.lineinfile:
    path: /home/{{ ansible_user }}/.zshrc
    line: "source $ZSH/oh-my-zsh.sh"

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    depth: 1

- name: Change user shell to zsh 
  shell: "chsh -s $(which zsh)"

