- name: vim get config
  get_url:
    url: https://raw.githubusercontent.com/matusstafura/dotfiles/refs/heads/main/vim/vimrc
    dest: /home/{{ ansible_user }}/.vimrc
    owner: "{{ ansible_user }}"
  tags: vim
  
- name: Ensure ~/.vim/plugged directory exists
  become: yes
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.vim/plugged
    owner: "{{ ansible_user }}"
    state: directory
    mode: '0755'

- name: Ensure ~/.vim/autoload directory exists
  become: yes
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.vim/autoload
    owner: "{{ ansible_user }}"
    state: directory
    mode: '0755'

- name: Install vim plugins
  shell: vim -c 'PlugInstall' -c 'qa!'
  args:
    chdir: /home/{{ ansible_user }}/.vim
  tags: vim

- name: get powerlevel10k config
  get_url:
    url: https://raw.githubusercontent.com/matusstafura/dotfiles/refs/heads/main/zsh/p10k.zsh
    dest: /home/{{ ansible_user }}/.oh-my-zsh/custom/themes/powerlevel10k.zsh
    owner: "{{ ansible_user }}"
  tags: zsh
