- hosts: localhost
  name: mini
  become: true
  pre_tasks:
    - name: Update cache
      apt:
        force_apt_get: true
        update_cache: true
  tasks:
    - name: install zsh
      include_tasks:
        file: tasks/zsh.yaml
      tags: zsh
    - name: install vim
      include_tasks:
        file: tasks/vim.yaml
      tags: vim
